### ISSUE TITLE
Demolition Range 

### ISSUE THREAD

**Issue by StrejdaJoe** [Piraj/PRJ_BootCamp#7]
Hi sweetheart,

I wondered if you could add a demolition range to the bootcamp. This range would be used for AT, CSW and EOD training, including using UAVs and other vehicles for mine detection/disposal. Also, there should be at least two buildings that could be used for controlled demolition. And one last thing, I'd love if you could add a notebook and an interactive screen where we could show some materials regarding AT, CSW and EOD training.

I'm looking forward to next version
Yours truly
[KYC]UncleJoe

**Comment by Piraj** [comment]
@StrejdaJoe Should the mines be already placed and if so are training mines enough? By other vehicles do you mean strykers and the like? because that means the range is gonna be rather big.

**Comment by StrejdaJoe** [comment]
@Piraj There is no need for mines to be placed, just need an area where i can place them as zeus. By other vehicles I mean Spanish Husky, Stryker etc., so that players can try, how those work. If there wouldnť be any suitable place, I'll find other solution for vehicle tryouts.
